### ISSUE TITLE
docker run hairyhenderson/gomplate --version doesn't print version

### ISSUE THREAD

**Issue by yizhiheng** [hairyhenderson/gomplate#266]
`docker run hairyhenderson/gomplate --version` only prints:
```
gomplate version
```
there's no actual version number...😢

**Comment by hairyhenderson** [comment]
Thanks for logging this @yizhiheng!

I think this was broken in v2.2.0, and fixed in v2.3.0:

```
$ docker run --rm hairyhenderson/gomplate:v2.1.0 --version
gomplate version 2.1.0
$ docker run --rm hairyhenderson/gomplate:v2.2.0 --version
gomplate version 
$ docker run --rm hairyhenderson/gomplate:v2.3.0 --version
gomplate version 2.3.0
$ docker run --rm hairyhenderson/gomplate:latest --version
gomplate version 2.3.0
```

Maybe do a `docker pull hairyhenderson/gomplate` and re-try?

**Comment by yizhiheng** [comment]
Thanks for your reply...🙂

I did `docker pull hairyhenderson/gomplate`, but `docker run hairyhenderson/gomplate:latest --version` still not showing the version number
```
$ docker pull hairyhenderson/gomplate:latest
latest: Pulling from hairyhenderson/gomplate
Digest: sha256:5b7093119d40ca5f4a1c308e7d538a592c2d22922281d0b2e095abff1d520879
Status: Image is up to date for hairyhenderson/gomplate:latest

$ docker run hairyhenderson/gomplate:v2.1.0 --version
gomplate version 2.1.0

$ docker run hairyhenderson/gomplate:v2.2.0 --version
gomplate version

$ docker run hairyhenderson/gomplate:v2.3.0 --version
gomplate version 2.3.0

$ docker run hairyhenderson/gomplate:latest --version
gomplate version
```

**Comment by hairyhenderson** [comment]
Ah, indeed. I was the one with an out-of-date image 😂.

I think this may actually be "normal" - the `latest` tag tracks the very latest commit in `master`, and only builds that are on a released git tag will actually have a version number.

What you probably want to do is stick with a released image, like `hairyhenderson/gomplate:v2.3.0`.

On the other hand - it _would_ be useful to report at least some kind of an indicator that it's an un-released version (maybe the Git SHA it was built from?)... 🤔

**Comment by yizhiheng** [comment]
OK, I thought `latest` meant the `latest released` version. I will stick with a released image tho.
